- name: Include "{{ansible_os_family}}" tasks
  include: "{{ansible_os_family}}.yml"

- name: Create directory for the docker certs
  file:
    path: "/opt/docker_registry/certs"
    state: directory

- name: Include "{{docker_type_of_node}}" docker recipe
  include: "{{docker_type_of_node}}.yml"
